apiVersion: v1
kind: Secret
metadata:
  name: webex-receiver
  namespace: {{ .Release.namespace }}
  labels:
    app: webex-receiver
type: Opaque
data:
  WEBEX_TOKEN: {{ default "" .Values.webex.token | b64enc | quote}}
  WEBEX_ROOM: {{ default "" .Values.webex.room | b64enc | quote }}